version: '3.5'

services:
  backend:
    image: backend
    build: .
    ports:
    - 8000:8000
    environment:
    - DB_USERNAME=example
    - DB_PASSWORD=example
    - DB_NAME=example
    - DB_HOST=db
    depends_on: 
    - db
    container_name: backend

  frontend:
    image: frontend
    build: .
    ports:
    - 5000:5000
    container_name: frontend

  db:
    image: postgres
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=example
    - POSTGRES_PASSWORD=example
    - POSTGRES_DB=example
    volumes:
    - ./data:/var/lib/postgresql/data
    container_name: db

volumes:
  data: