version: '3.5'

services:
  backend:
    image: backend
    build: .
    ports:
    - 8000:8000
    container_name: backend

  frontend:
    image: frontend
    build: .
    ports:
    - 5000:5000
    container_name: frontend