version: '3.5'

services:
  frontend:
    image: ml-frontend
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
    - 3000:3000
    container_name: frontend

  backend:
    image: ml-backend
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
    - 5000:5000
    volumes:
    - ./mymodel:/src/model
    container_name: backend

  training:
    image: ml-training
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
    - ./mymodel:/src/model
    - ./myimages:/src/imgs
    depends_on:
    - backend
    container_name: training

volumes:
  mymodel:
  myimages: